# Generated by Django 4.0.6 on 2022-10-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cryptocurrency', models.CharField(max_length=255)),
                ('Amount', models.CharField(max_length=255)),
            ],
        ),
    ]
